server:
  port: 8090


eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}
    register-with-eureka: false
    fetch-registry: false
